plugins:
  - remark-preset-lint-markdown-style-guide
  - remark-preset-lint-recommended
  - remark-preset-lint-consistent
  - # Save space
    - remark-lint-list-item-spacing
    - false
  - # Save space
    - remark-lint-list-item-indent
    - space
  - # Save space
    - remark-lint-maximum-line-length
    - 150
