name: Test Commit
on:
  push:
    branches:
      - test-github-actions
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Lint by commitlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Install commitlint
        run: sudo npm install -g @commitlint/{cli,config-conventional}
      - name: Display commitlint
        run: commitlint --version
      - name: Fetch base branch
        run: git fetch --no-tags --depth=1 origin main
      - name: Run commitlint
        run: commitlint --from $(git merge-base origin/main HEAD) --to ${{ github.sha }} --verbose
      - name: Run commitlint for pull request
        run: echo "${TITLE}" | commitlint --verbose
        env:
          TITLE: ${{ github.event.pull_request.title }}
