name: Test JSON
on:
  push:
    branches:
      - release-*
      - test-github-actions
  pull_request:
    paths:
      - '**.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jsonlint:
    name: Lint by jsonlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install jsonlint
        run: sudo npm install -g jsonlint
      - name: Display jsonlint
        # jsonlint --version return code is 1
        run: jsonlint --version || true
      - name: Run jsonlint
        run: find . -name '*.json' | xargs -I {} jsonlint --quiet --compact {}

  prettier:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prettier
        run: sudo npm install -g prettier
      - name: Display prettier
        run: prettier --version
      - name: Run prettier
        run: prettier --check --parser=json '**/*.json'
