name: Test Markdown
on:
  push:
    branches:
      - test-github-actions
  pull_request:
    paths:
      - '**.md'
      - '!CHANGELOG.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint by markdownlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Display markdownlint
        run: markdownlint --version
      - name: Run markdownlint
        run: markdownlint --dot '**/*.md'

  format:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prettier
        run: sudo npm install -g prettier
      - name: Display prettier
        run: prettier --version
      - name: Run prettier
        run: prettier --check --parser=markdown '**/*.md'
