name: Test Shell
on:
  push:
    branches:
      - release-*
      - test-github-actions
  pull_request:
    paths:
      - '**.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: Lint by shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # use pre-installed shellcheck
      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
      - name: Display shellcheck
        run: shellcheck --version
      - name: Run shellcheck
        run: find . -name '*.sh' | xargs shellcheck

  shfmt:
    name: Format by shfmt
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install shfmt
        run: docker pull mvdan/shfmt
      - name: Display shfmt
        run: docker run --rm mvdan/shfmt --version
      - name: Run shfmt
        run: docker run --rm -v $(pwd):/work -w /work mvdan/shfmt -i 2 -ci -bn -d .
