name: Test Secret
on:
  push:
    branches:
      - release-*
      - test-github-actions
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secretlint:
    name: Lint by secretlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install secretlint
        run: docker pull secretlint/secretlint
      - name: Display secretlint
        run: docker run --rm secretlint/secretlint secretlint --version
      - name: Run secretlint
        run: docker run --rm -v $(pwd):/work -w /work secretlint/secretlint secretlint '**/*'

  gitleaks:
    name: Lint by gitleaks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Install gitleaks
        run: docker pull zricethezav/gitleaks
      - name: Display gitleaks
        run: docker run --rm zricethezav/gitleaks --version
      - name: Fetch base branch
        run: git fetch --no-tags --depth=1 origin main
      - name: Run gitleaks
        run: |
          docker run --rm -v $(pwd):/work -w /work zricethezav/gitleaks --path=/work -v --redact \
          --commit-to=$(git merge-base origin/main HEAD)
